# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c586f8795b70e0ee658de35a2f468e39060da68b82f880193b602bb070ceca8a08091da38b13c6dc7933ee24e93a2bbb961c2c41278926c881e2e46987538669

test:
  secret_key_base: 6f65668ac32259f6ebb743249bed0aa74338d372a6b1ad9a7703d7601cc72d7f2f9de766447c2ee6e02bb6b54977123f5999e58293353384ef2dbd16c149d72d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
